### ISSUE TITLE
Carthage: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by PH9** [uber/ios-snapshot-test-case#94]
- Xcode 11 Beta 2 (11M337n)
- macOS 10.15 Beta (19A487l)
- Carthage 0.33.0

Using command:

`carthage update --platform iOS --no-use-binaries`

Result when run unit tests.

```
Ld /Users/u/p/DerivedData/iOS/Build/Products/Debug-iphonesimulator/iOS.app/PlugIns/iOSTests.xctest/iOSTests normal x86_64 (in target: iOSTests)
    cd /Users/u/p
    /Users/w/Xcode/Xcode-11-beta-2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios13.0-simulator -bundle -isysroot /Users/w/Xcode/Xcode-11-beta-2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk -L/Users/u/p/DerivedData/iOS/Build/Products/Debug-iphonesimulator -F/Users/u/p/DerivedData/iOS/Build/Products/Debug-iphonesimulator -L/Users/w/Xcode/Xcode-11-beta-2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib -F/Users/w/Xcode/Xcode-11-beta-2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -filelist /Users/u/p/DerivedData/iOS/Build/Intermediates.noindex/iOS.build/Debug-iphonesimulator/iOSTests.build/Objects-normal/x86_64/iOSTests.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -bundle_loader /Users/u/p/DerivedData/iOS/Build/Products/Debug-iphonesimulator/iOS.app/iOS -Xlinker -object_path_lto -Xlinker /Users/u/p/DerivedData/iOS/Build/Intermediates.noindex/iOS.build/Debug-iphonesimulator/iOSTests.build/Objects-normal/x86_64/iOSTests_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -fprofile-instr-generate -L/Users/w/Xcode/Xcode-11-beta-2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/u/p/DerivedData/iOS/Build/Intermediates.noindex/iOS.build/Debug-iphonesimulator/iOSTests.build/Objects-normal/x86_64/iOSTests.swiftmodule -framework XCTest -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/u/p/DerivedData/iOS/Build/Intermediates.noindex/iOS.build/Debug-iphonesimulator/iOSTests.build/iOSTests.xctest-Simulated.xcent -Xlinker -dependency_info -Xlinker /Users/u/p/DerivedData/iOS/Build/Intermediates.noindex/iOS.build/Debug-iphonesimulator/iOSTests.build/Objects-normal/x86_64/iOSTests_dependency_info.dat -o /Users/u/p/DerivedData/iOS/Build/Products/Debug-iphonesimulator/iOS.app/PlugIns/iOSTests.xctest/iOSTests

ld: warning: Could not find or use auto-linked framework 'FBSnapshotTestCase'
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBSnapshotTestCase", referenced from:
      type metadata for iOSTests.TestCase in TestCase.o
  "_OBJC_METACLASS_$_FBSnapshotTestCase", referenced from:
      _OBJC_METACLASS_$__TtC8iOSTests8TestCase in TestCase.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by reidmain** [comment]
Does Carthage support Xcode 11 and macOS 10.15 betas?

Our [Carthage demo](https://github.com/uber/ios-snapshot-test-case/tree/master/iOSSnapshotTestCaseCarthageDemo) looks to compile using the Xcode 11 beta on macOS 10.14.

**Comment by PH9** [comment]
Not sure, but [Alamofire](https://github.com/Alamofire/Alamofire) work fine.

Or you suggest me to open issue in [Carthage](https://github.com/Carthage/Carthage/issues) ?

**Comment by PH9** [comment]
I have try follow the [Carthage Demo](https://github.com/uber/ios-snapshot-test-case/tree/master/iOSSnapshotTestCaseCarthageDemo), and it can run for now. 

But unit test still fail. If success I'll close this issue later

**Comment by PH9** [comment]
I got this console log. Can anyone help me ?

```
2019-07-01 15:30:02.392152+0700 iOS[99016:6494752] The bundle “iOSTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2019-07-01 15:30:02.392255+0700 iOS[99016:6494752] (dlopen_preflight(/Users/w/ios-meetup/DerivedData/iOS/Build/Products/Debug-iphonesimulator/iOS.app/PlugIns/iOSTests.xctest/iOSTests): Library not loaded: @rpath/FBSnapshotTestCase.framework/FBSnapshotTestCase
  Referenced from: /Users/w/ios-meetup/DerivedData/iOS/Build/Products/Debug-iphonesimulator/iOS.app/PlugIns/iOSTests.xctest/iOSTests
  Reason: image not found)
```

**Comment by PH9** [comment]
It works now Thanks.

**Comment by scottkicks** [comment]
what was your solution @PH9 ?

**Comment by PH9** [comment]
> what was your solution @PH9 ?

Sorry, I cannot remember it was 3 years ago.

May be I just compare my projects/workspaces with the demo https://github.com/uber/ios-snapshot-test-case/tree/main/demos/iOSSnapshotTestCaseCarthageDemo
